// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {service} from '../models';

export function Devices():Promise<Array<domain.AdbDevice>>;

export function InstallApk(arg1:service.InstallApkRequest):Promise<string>;

export function KillServer():Promise<void>;

export function Pull(arg1:service.PullRequest):Promise<string>;

export function Push(arg1:service.PushRequest):Promise<string>;

export function Remount(arg1:string):Promise<string>;

export function Root(arg1:string):Promise<string>;

export function Shell(arg1:string,arg2:string):Promise<string>;

export function StartLogcat(arg1:service.LogcatRequest):Promise<string>;

export function StartServer():Promise<void>;
