// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Devices() {
  return window['go']['service']['AdbService']['Devices']();
}

export function InstallApk(arg1) {
  return window['go']['service']['AdbService']['InstallApk'](arg1);
}

export function KillServer() {
  return window['go']['service']['AdbService']['KillServer']();
}

export function LogcatSnapshot(arg1, arg2, arg3) {
  return window['go']['service']['AdbService']['LogcatSnapshot'](arg1, arg2, arg3);
}

export function Pull(arg1) {
  return window['go']['service']['AdbService']['Pull'](arg1);
}

export function Push(arg1) {
  return window['go']['service']['AdbService']['Push'](arg1);
}

export function Remount(arg1) {
  return window['go']['service']['AdbService']['Remount'](arg1);
}

export function Root(arg1) {
  return window['go']['service']['AdbService']['Root'](arg1);
}

export function Shell(arg1, arg2) {
  return window['go']['service']['AdbService']['Shell'](arg1, arg2);
}

export function StartLogcat(arg1) {
  return window['go']['service']['AdbService']['StartLogcat'](arg1);
}

export function StartServer() {
  return window['go']['service']['AdbService']['StartServer']();
}

export function StopLogcat(arg1) {
  return window['go']['service']['AdbService']['StopLogcat'](arg1);
}
