// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function Create(arg1:domain.AvdSpec):Promise<string>;

export function Delete(arg1:string):Promise<string>;

export function InstallImage(arg1:string):Promise<string>;

export function List():Promise<Array<domain.AvdSummary>>;

export function ListImages(arg1:boolean):Promise<Array<domain.SystemImage>>;

export function ListProfiles(arg1:boolean):Promise<Array<domain.DeviceProfile>>;

export function ValidateName(arg1:string):Promise<domain.NameValidation>;
