// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1) {
  return window['go']['service']['AvdService']['Create'](arg1);
}

export function Delete(arg1) {
  return window['go']['service']['AvdService']['Delete'](arg1);
}

export function DeleteImage(arg1) {
  return window['go']['service']['AvdService']['DeleteImage'](arg1);
}

export function InstallImage(arg1) {
  return window['go']['service']['AvdService']['InstallImage'](arg1);
}

export function List() {
  return window['go']['service']['AvdService']['List']();
}

export function ListImages(arg1) {
  return window['go']['service']['AvdService']['ListImages'](arg1);
}

export function ListProfiles(arg1) {
  return window['go']['service']['AvdService']['ListProfiles'](arg1);
}

export function ValidateName(arg1) {
  return window['go']['service']['AvdService']['ValidateName'](arg1);
}
