// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';
import {domain} from '../models';

export function Clone(arg1:service.CloneRequest):Promise<string>;

export function ComputeCommand(arg1:domain.AvdSpec):Promise<Record<string, string>>;

export function ConfigSchemaMetadata():Promise<Record<string, any>>;

export function Create(arg1:domain.AvdSpec):Promise<string>;

export function Delete(arg1:service.DeleteRequest):Promise<string>;

export function Get(arg1:string):Promise<domain.AvdDetail>;

export function List():Promise<Array<domain.AvdSummary>>;

export function ListConfigSchema():Promise<Array<domain.HwConfigItem>>;

export function ListImages(arg1:boolean):Promise<Array<domain.SystemImage>>;

export function ListProfiles(arg1:boolean):Promise<Array<domain.DeviceProfile>>;

export function ReadConfigRaw(arg1:string):Promise<string>;

export function Rename(arg1:string,arg2:string):Promise<void>;

export function SnapshotDir(arg1:string):Promise<string>;

export function Update(arg1:string,arg2:domain.AvdPatch):Promise<void>;

export function ValidateName(arg1:string):Promise<domain.NameValidation>;

export function WipeData(arg1:string):Promise<string>;

export function WriteConfigRaw(arg1:service.WriteConfigRawRequest):Promise<domain.ConfigDiff>;
