// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Clone(arg1) {
  return window['go']['service']['AvdService']['Clone'](arg1);
}

export function ComputeCommand(arg1) {
  return window['go']['service']['AvdService']['ComputeCommand'](arg1);
}

export function ConfigSchemaMetadata() {
  return window['go']['service']['AvdService']['ConfigSchemaMetadata']();
}

export function Create(arg1) {
  return window['go']['service']['AvdService']['Create'](arg1);
}

export function Delete(arg1) {
  return window['go']['service']['AvdService']['Delete'](arg1);
}

export function Get(arg1) {
  return window['go']['service']['AvdService']['Get'](arg1);
}

export function List() {
  return window['go']['service']['AvdService']['List']();
}

export function ListConfigSchema() {
  return window['go']['service']['AvdService']['ListConfigSchema']();
}

export function ListImages(arg1) {
  return window['go']['service']['AvdService']['ListImages'](arg1);
}

export function ListProfiles(arg1) {
  return window['go']['service']['AvdService']['ListProfiles'](arg1);
}

export function ReadConfigRaw(arg1) {
  return window['go']['service']['AvdService']['ReadConfigRaw'](arg1);
}

export function Rename(arg1, arg2) {
  return window['go']['service']['AvdService']['Rename'](arg1, arg2);
}

export function SnapshotDir(arg1) {
  return window['go']['service']['AvdService']['SnapshotDir'](arg1);
}

export function Update(arg1, arg2) {
  return window['go']['service']['AvdService']['Update'](arg1, arg2);
}

export function ValidateName(arg1) {
  return window['go']['service']['AvdService']['ValidateName'](arg1);
}

export function WipeData(arg1) {
  return window['go']['service']['AvdService']['WipeData'](arg1);
}

export function WriteConfigRaw(arg1) {
  return window['go']['service']['AvdService']['WriteConfigRaw'](arg1);
}
