// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function AppVersion():Promise<string>;

export function ClearCache():Promise<void>;

export function EnvSummary():Promise<domain.DiagnosticReport>;

export function ExportReport():Promise<string>;

export function LogDir():Promise<string>;

export function LogFiles():Promise<Array<string>>;

export function LogLevel():Promise<string>;

export function OpenLogFolder():Promise<void>;

export function ReadAppLog(arg1:number):Promise<Array<domain.LogLine>>;

export function RunSelfCheck():Promise<string>;

export function SetLogLevel(arg1:string):Promise<void>;

export function TestLog(arg1:string):Promise<string>;
