// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppVersion() {
  return window['go']['service']['DiagnosticsService']['AppVersion']();
}

export function ClearCache() {
  return window['go']['service']['DiagnosticsService']['ClearCache']();
}

export function EnvSummary() {
  return window['go']['service']['DiagnosticsService']['EnvSummary']();
}

export function ExportReport() {
  return window['go']['service']['DiagnosticsService']['ExportReport']();
}

export function OpenLogFolder() {
  return window['go']['service']['DiagnosticsService']['OpenLogFolder']();
}

export function ReadAppLog(arg1) {
  return window['go']['service']['DiagnosticsService']['ReadAppLog'](arg1);
}

export function RunSelfCheck() {
  return window['go']['service']['DiagnosticsService']['RunSelfCheck']();
}
