// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Active() {
  return window['go']['service']['DisplayService']['Active']();
}

export function Close(arg1) {
  return window['go']['service']['DisplayService']['Close'](arg1);
}

export function NativeSupported() {
  return window['go']['service']['DisplayService']['NativeSupported']();
}

export function Open(arg1) {
  return window['go']['service']['DisplayService']['Open'](arg1);
}

export function OpenNative(arg1) {
  return window['go']['service']['DisplayService']['OpenNative'](arg1);
}

export function SendKey(arg1, arg2) {
  return window['go']['service']['DisplayService']['SendKey'](arg1, arg2);
}

export function SendTouch(arg1, arg2, arg3, arg4) {
  return window['go']['service']['DisplayService']['SendTouch'](arg1, arg2, arg3, arg4);
}

export function Shutdown() {
  return window['go']['service']['DisplayService']['Shutdown']();
}
