// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';

export function Active():Promise<Array<string>>;

export function Close(arg1:string):Promise<void>;

export function NativeSupported():Promise<boolean>;

export function Open(arg1:string):Promise<service.DisplaySession>;

export function OpenNative(arg1:string):Promise<service.DisplaySession>;

export function SendKey(arg1:string,arg2:string):Promise<void>;

export function SendTouch(arg1:string,arg2:number,arg3:number,arg4:boolean):Promise<void>;

export function Shutdown():Promise<void>;
