// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {service} from '../models';

export function ListRunning():Promise<Array<domain.EmulatorInstance>>;

export function Shutdown(arg1:boolean):Promise<void>;

export function Start(arg1:service.StartRequest):Promise<domain.EmulatorInstance>;

export function Stop(arg1:string,arg2:boolean):Promise<void>;

export function StopByAvd(arg1:string,arg2:boolean):Promise<void>;
