// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLog(arg1, arg2) {
  return window['go']['service']['EmulatorService']['GetLog'](arg1, arg2);
}

export function ListRunning() {
  return window['go']['service']['EmulatorService']['ListRunning']();
}

export function Restart(arg1, arg2) {
  return window['go']['service']['EmulatorService']['Restart'](arg1, arg2);
}

export function Rotate(arg1, arg2) {
  return window['go']['service']['EmulatorService']['Rotate'](arg1, arg2);
}

export function Screenshot(arg1) {
  return window['go']['service']['EmulatorService']['Screenshot'](arg1);
}

export function SendKey(arg1, arg2) {
  return window['go']['service']['EmulatorService']['SendKey'](arg1, arg2);
}

export function SetBattery(arg1, arg2, arg3) {
  return window['go']['service']['EmulatorService']['SetBattery'](arg1, arg2, arg3);
}

export function SetGps(arg1, arg2, arg3) {
  return window['go']['service']['EmulatorService']['SetGps'](arg1, arg2, arg3);
}

export function SetNetwork(arg1, arg2, arg3) {
  return window['go']['service']['EmulatorService']['SetNetwork'](arg1, arg2, arg3);
}

export function Shutdown(arg1) {
  return window['go']['service']['EmulatorService']['Shutdown'](arg1);
}

export function Start(arg1) {
  return window['go']['service']['EmulatorService']['Start'](arg1);
}

export function Stop(arg1, arg2) {
  return window['go']['service']['EmulatorService']['Stop'](arg1, arg2);
}

export function StopByAvd(arg1, arg2) {
  return window['go']['service']['EmulatorService']['StopByAvd'](arg1, arg2);
}
