// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListRunning() {
  return window['go']['service']['EmulatorService']['ListRunning']();
}

export function Shutdown(arg1) {
  return window['go']['service']['EmulatorService']['Shutdown'](arg1);
}

export function Start(arg1) {
  return window['go']['service']['EmulatorService']['Start'](arg1);
}

export function Stop(arg1, arg2) {
  return window['go']['service']['EmulatorService']['Stop'](arg1, arg2);
}

export function StopByAvd(arg1, arg2) {
  return window['go']['service']['EmulatorService']['StopByAvd'](arg1, arg2);
}
