// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckAcceleration() {
  return window['go']['service']['EnvService']['CheckAcceleration']();
}

export function CopyToClipboard(arg1) {
  return window['go']['service']['EnvService']['CopyToClipboard'](arg1);
}

export function Detect(arg1) {
  return window['go']['service']['EnvService']['Detect'](arg1);
}

export function DetectJava() {
  return window['go']['service']['EnvService']['DetectJava']();
}

export function DetectSdkRoots() {
  return window['go']['service']['EnvService']['DetectSdkRoots']();
}

export function DiskSpace(arg1) {
  return window['go']['service']['EnvService']['DiskSpace'](arg1);
}

export function EnabledWindowsFeatures() {
  return window['go']['service']['EnvService']['EnabledWindowsFeatures']();
}

export function HostInfo() {
  return window['go']['service']['EnvService']['HostInfo']();
}

export function OpenExternalURL(arg1) {
  return window['go']['service']['EnvService']['OpenExternalURL'](arg1);
}

export function OpenInExplorer(arg1) {
  return window['go']['service']['EnvService']['OpenInExplorer'](arg1);
}

export function OpenTerminal(arg1) {
  return window['go']['service']['EnvService']['OpenTerminal'](arg1);
}

export function PickDirectory(arg1) {
  return window['go']['service']['EnvService']['PickDirectory'](arg1);
}

export function PickFile(arg1) {
  return window['go']['service']['EnvService']['PickFile'](arg1);
}

export function ResolveAvdHome() {
  return window['go']['service']['EnvService']['ResolveAvdHome']();
}

export function ResolvedPaths() {
  return window['go']['service']['EnvService']['ResolvedPaths']();
}

export function SaveFile(arg1) {
  return window['go']['service']['EnvService']['SaveFile'](arg1);
}

export function ValidateSdkRoot(arg1) {
  return window['go']['service']['EnvService']['ValidateSdkRoot'](arg1);
}
