// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {service} from '../models';

export function Check():Promise<domain.EnvReport>;

export function CopyToClipboard(arg1:string):Promise<void>;

export function Prepare():Promise<string>;

export function Repair():Promise<string>;

export function Resolved():Promise<service.ResolvedPaths>;
