// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Check() {
  return window['go']['service']['EnvService']['Check']();
}

export function CopyToClipboard(arg1) {
  return window['go']['service']['EnvService']['CopyToClipboard'](arg1);
}

export function Prepare() {
  return window['go']['service']['EnvService']['Prepare']();
}

export function Resolved() {
  return window['go']['service']['EnvService']['Resolved']();
}
