// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Cancel(arg1) {
  return window['go']['service']['JobService']['Cancel'](arg1);
}

export function CancelAll() {
  return window['go']['service']['JobService']['CancelAll']();
}

export function List() {
  return window['go']['service']['JobService']['List']();
}

export function Logs(arg1, arg2) {
  return window['go']['service']['JobService']['Logs'](arg1, arg2);
}
