// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function Cancel(arg1:string):Promise<void>;

export function CancelAll():Promise<void>;

export function Get(arg1:string):Promise<domain.JobInfo>;

export function List():Promise<Array<domain.JobInfo>>;

export function Logs(arg1:string,arg2:number):Promise<Array<domain.LogLine>>;

export function PruneAsk(arg1:number):Promise<void>;
