// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddSource(arg1) {
  return window['go']['service']['MirrorService']['AddSource'](arg1);
}

export function CancelTest(arg1) {
  return window['go']['service']['MirrorService']['CancelTest'](arg1);
}

export function GetCachedResults() {
  return window['go']['service']['MirrorService']['GetCachedResults']();
}

export function ListSources() {
  return window['go']['service']['MirrorService']['ListSources']();
}

export function ProbeSource(arg1) {
  return window['go']['service']['MirrorService']['ProbeSource'](arg1);
}

export function RemoveSource(arg1) {
  return window['go']['service']['MirrorService']['RemoveSource'](arg1);
}

export function SetActiveSource(arg1) {
  return window['go']['service']['MirrorService']['SetActiveSource'](arg1);
}

export function TestAllQuick() {
  return window['go']['service']['MirrorService']['TestAllQuick']();
}

export function TestSources(arg1) {
  return window['go']['service']['MirrorService']['TestSources'](arg1);
}

export function UpdateSource(arg1) {
  return window['go']['service']['MirrorService']['UpdateSource'](arg1);
}
