// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function Active():Promise<domain.MirrorSource>;

export function ActiveJDK():Promise<domain.MirrorSource>;

export function Check(arg1:string):Promise<domain.MirrorCheck>;

export function CheckAll():Promise<Array<domain.MirrorCheck>>;

export function CheckJDK(arg1:string):Promise<domain.MirrorCheck>;

export function CheckJDKAll():Promise<Array<domain.MirrorCheck>>;

export function ListJDKSources():Promise<Array<domain.MirrorSource>>;

export function ListSources():Promise<Array<domain.MirrorSource>>;

export function SetActiveJDKSource(arg1:string):Promise<domain.MirrorSource>;

export function SetActiveSource(arg1:string):Promise<domain.MirrorSource>;
