// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Active() {
  return window['go']['service']['MirrorService']['Active']();
}

export function ActiveJDK() {
  return window['go']['service']['MirrorService']['ActiveJDK']();
}

export function Check(arg1) {
  return window['go']['service']['MirrorService']['Check'](arg1);
}

export function CheckAll() {
  return window['go']['service']['MirrorService']['CheckAll']();
}

export function CheckJDK(arg1) {
  return window['go']['service']['MirrorService']['CheckJDK'](arg1);
}

export function CheckJDKAll() {
  return window['go']['service']['MirrorService']['CheckJDKAll']();
}

export function ListJDKSources() {
  return window['go']['service']['MirrorService']['ListJDKSources']();
}

export function ListSources() {
  return window['go']['service']['MirrorService']['ListSources']();
}

export function SetActiveJDKSource(arg1) {
  return window['go']['service']['MirrorService']['SetActiveJDKSource'](arg1);
}

export function SetActiveSource(arg1) {
  return window['go']['service']['MirrorService']['SetActiveSource'](arg1);
}
