// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';
import {domain} from '../models';

export function AddSource(arg1:service.AddSourceRequest):Promise<domain.MirrorSource>;

export function CancelTest(arg1:string):Promise<void>;

export function GetCachedResults():Promise<Array<domain.SpeedResult>>;

export function ListSources():Promise<Array<domain.MirrorSource>>;

export function ProbeSource(arg1:string):Promise<domain.SpeedResult>;

export function RemoveSource(arg1:string):Promise<void>;

export function SetActiveSource(arg1:string):Promise<void>;

export function TestAllQuick():Promise<string>;

export function TestSources(arg1:service.TestRequest):Promise<string>;

export function UpdateSource(arg1:service.UpdateSourceRequest):Promise<domain.MirrorSource>;
