// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';
import {domain} from '../models';

export function AcceptLicenses(arg1:Array<string>):Promise<void>;

export function BootstrapCmdlineTools(arg1:service.BootstrapRequest):Promise<string>;

export function Install(arg1:service.InstallRequest):Promise<string>;

export function IsSourceUsable():Promise<Record<string, any>>;

export function ListInstalled():Promise<Array<domain.SdkPackage>>;

export function ListLicenses(arg1:Array<string>):Promise<Array<domain.License>>;

export function ListRemote(arg1:service.ListRemoteRequest):Promise<Array<domain.SdkPackage>>;

export function ListSystemImages(arg1:service.ListSystemImagesRequest):Promise<Array<domain.SystemImage>>;

export function PlanInstall(arg1:service.InstallRequest):Promise<domain.InstallPlan>;

export function SystemImageTags(arg1:service.ListRemoteRequest):Promise<Array<service.SysImgTagAvailability>>;

export function Uninstall(arg1:service.UninstallRequest):Promise<string>;

export function VerifyPackage(arg1:string):Promise<domain.VerifyResult>;
