// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptLicenses(arg1) {
  return window['go']['service']['SdkService']['AcceptLicenses'](arg1);
}

export function BootstrapCmdlineTools(arg1) {
  return window['go']['service']['SdkService']['BootstrapCmdlineTools'](arg1);
}

export function Install(arg1) {
  return window['go']['service']['SdkService']['Install'](arg1);
}

export function IsSourceUsable() {
  return window['go']['service']['SdkService']['IsSourceUsable']();
}

export function ListInstalled() {
  return window['go']['service']['SdkService']['ListInstalled']();
}

export function ListLicenses(arg1) {
  return window['go']['service']['SdkService']['ListLicenses'](arg1);
}

export function ListRemote(arg1) {
  return window['go']['service']['SdkService']['ListRemote'](arg1);
}

export function ListSystemImages(arg1) {
  return window['go']['service']['SdkService']['ListSystemImages'](arg1);
}

export function PlanInstall(arg1) {
  return window['go']['service']['SdkService']['PlanInstall'](arg1);
}

export function SystemImageTags(arg1) {
  return window['go']['service']['SdkService']['SystemImageTags'](arg1);
}

export function Uninstall(arg1) {
  return window['go']['service']['SdkService']['Uninstall'](arg1);
}

export function VerifyPackage(arg1) {
  return window['go']['service']['SdkService']['VerifyPackage'](arg1);
}
