// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function Get():Promise<domain.AppSettings>;

export function Path():Promise<string>;

export function Reset(arg1:string):Promise<domain.AppSettings>;

export function Update(arg1:Record<string, any>):Promise<domain.AppSettings>;
