// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Get() {
  return window['go']['service']['SettingsService']['Get']();
}

export function Info() {
  return window['go']['service']['SettingsService']['Info']();
}

export function Path() {
  return window['go']['service']['SettingsService']['Path']();
}

export function Reset() {
  return window['go']['service']['SettingsService']['Reset']();
}

export function Update(arg1) {
  return window['go']['service']['SettingsService']['Update'](arg1);
}
