// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['service']['WindowService']['Close']();
}

export function IsMaximised() {
  return window['go']['service']['WindowService']['IsMaximised']();
}

export function Minimise() {
  return window['go']['service']['WindowService']['Minimise']();
}

export function ToggleMaximise() {
  return window['go']['service']['WindowService']['ToggleMaximise']();
}
