// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close():Promise<void>;

export function IsMaximised():Promise<boolean>;

export function Minimise():Promise<void>;

export function ToggleMaximise():Promise<void>;
