// 模拟器 gRPC 控制通道的最小 proto 子集（仅保留自定义 UI 画面接管用到的三个 rpc）。
//
// 消息字段号/类型来自模拟器 37.1.11.0 的 gRPC 反射 dump，必须逐字保持一致，
// 否则序列化结果会被服务端忽略（尤其注意 pressure / touch_major / touch_minor 是 int32，不是 float）。
//
// 同版本的官方全文同名文件随 SDK 一起发布（gitignore 的 build/bin 下）：
// build/bin/sdk/emulator/lib/emulator_controller.proto —— 修改本文件时应与它核对字段号与类型。
//
// 重新生成命令（Windows，protoc 25.3；-I 第二项是 protobuf 自带的 well-known types 目录）：
//
//	go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.36.11
//	go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.5.1
//	protoc -I internal/emulatorgrpc/proto \
//	  -I "D:/DeveEnvironment/Program/Anaconda3/Library/include" \
//	  --go_out=paths=source_relative:internal/emulatorgrpc/pb \
//	  --go-grpc_out=paths=source_relative:internal/emulatorgrpc/pb \
//	  internal/emulatorgrpc/proto/emulator_controller.proto
//
// 注意：protoc / protoc-gen-go / protoc-gen-go-grpc 必须都在 PATH 中；在 Windows 上
// go install 的产物位于 %GOPATH%\bin（通常是 C:\Users\<用户>\go\bin）。

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.3
// source: emulator_controller.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EmulatorController_GetScreenshot_FullMethodName    = "/android.emulation.control.EmulatorController/getScreenshot"
	EmulatorController_StreamScreenshot_FullMethodName = "/android.emulation.control.EmulatorController/streamScreenshot"
	EmulatorController_SendTouch_FullMethodName        = "/android.emulation.control.EmulatorController/sendTouch"
)

// EmulatorControllerClient is the client API for EmulatorController service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// EmulatorController 是模拟器暴露的图像/输入控制接口。
type EmulatorControllerClient interface {
	// getScreenshot 取一张指定格式的截图（用于探测原生分辨率）。
	GetScreenshot(ctx context.Context, in *ImageFormat, opts ...grpc.CallOption) (*Image, error)
	// streamScreenshot 持续推送画面帧（脏帧驱动：画面静止时几乎不推帧）。
	StreamScreenshot(ctx context.Context, in *ImageFormat, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Image], error)
	// sendTouch 注入触点（按下/移动 expiration=1，抬起 expiration=0）。
	SendTouch(ctx context.Context, in *TouchEvent, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type emulatorControllerClient struct {
	cc grpc.ClientConnInterface
}

func NewEmulatorControllerClient(cc grpc.ClientConnInterface) EmulatorControllerClient {
	return &emulatorControllerClient{cc}
}

func (c *emulatorControllerClient) GetScreenshot(ctx context.Context, in *ImageFormat, opts ...grpc.CallOption) (*Image, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Image)
	err := c.cc.Invoke(ctx, EmulatorController_GetScreenshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emulatorControllerClient) StreamScreenshot(ctx context.Context, in *ImageFormat, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Image], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EmulatorController_ServiceDesc.Streams[0], EmulatorController_StreamScreenshot_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ImageFormat, Image]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EmulatorController_StreamScreenshotClient = grpc.ServerStreamingClient[Image]

func (c *emulatorControllerClient) SendTouch(ctx context.Context, in *TouchEvent, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, EmulatorController_SendTouch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmulatorControllerServer is the server API for EmulatorController service.
// All implementations must embed UnimplementedEmulatorControllerServer
// for forward compatibility.
//
// EmulatorController 是模拟器暴露的图像/输入控制接口。
type EmulatorControllerServer interface {
	// getScreenshot 取一张指定格式的截图（用于探测原生分辨率）。
	GetScreenshot(context.Context, *ImageFormat) (*Image, error)
	// streamScreenshot 持续推送画面帧（脏帧驱动：画面静止时几乎不推帧）。
	StreamScreenshot(*ImageFormat, grpc.ServerStreamingServer[Image]) error
	// sendTouch 注入触点（按下/移动 expiration=1，抬起 expiration=0）。
	SendTouch(context.Context, *TouchEvent) (*emptypb.Empty, error)
	mustEmbedUnimplementedEmulatorControllerServer()
}

// UnimplementedEmulatorControllerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEmulatorControllerServer struct{}

func (UnimplementedEmulatorControllerServer) GetScreenshot(context.Context, *ImageFormat) (*Image, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetScreenshot not implemented")
}
func (UnimplementedEmulatorControllerServer) StreamScreenshot(*ImageFormat, grpc.ServerStreamingServer[Image]) error {
	return status.Errorf(codes.Unimplemented, "method StreamScreenshot not implemented")
}
func (UnimplementedEmulatorControllerServer) SendTouch(context.Context, *TouchEvent) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendTouch not implemented")
}
func (UnimplementedEmulatorControllerServer) mustEmbedUnimplementedEmulatorControllerServer() {}
func (UnimplementedEmulatorControllerServer) testEmbeddedByValue()                            {}

// UnsafeEmulatorControllerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmulatorControllerServer will
// result in compilation errors.
type UnsafeEmulatorControllerServer interface {
	mustEmbedUnimplementedEmulatorControllerServer()
}

func RegisterEmulatorControllerServer(s grpc.ServiceRegistrar, srv EmulatorControllerServer) {
	// If the following call pancis, it indicates UnimplementedEmulatorControllerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EmulatorController_ServiceDesc, srv)
}

func _EmulatorController_GetScreenshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImageFormat)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmulatorControllerServer).GetScreenshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmulatorController_GetScreenshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmulatorControllerServer).GetScreenshot(ctx, req.(*ImageFormat))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmulatorController_StreamScreenshot_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ImageFormat)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EmulatorControllerServer).StreamScreenshot(m, &grpc.GenericServerStream[ImageFormat, Image]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EmulatorController_StreamScreenshotServer = grpc.ServerStreamingServer[Image]

func _EmulatorController_SendTouch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TouchEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmulatorControllerServer).SendTouch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmulatorController_SendTouch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmulatorControllerServer).SendTouch(ctx, req.(*TouchEvent))
	}
	return interceptor(ctx, in, info, handler)
}

// EmulatorController_ServiceDesc is the grpc.ServiceDesc for EmulatorController service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EmulatorController_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "android.emulation.control.EmulatorController",
	HandlerType: (*EmulatorControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getScreenshot",
			Handler:    _EmulatorController_GetScreenshot_Handler,
		},
		{
			MethodName: "sendTouch",
			Handler:    _EmulatorController_SendTouch_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "streamScreenshot",
			Handler:       _EmulatorController_StreamScreenshot_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "emulator_controller.proto",
}
