// 模拟器 gRPC 控制通道的最小 proto 子集（仅保留自定义 UI 画面接管用到的三个 rpc）。
//
// 消息字段号/类型来自模拟器 37.1.11.0 的 gRPC 反射 dump，必须逐字保持一致，
// 否则序列化结果会被服务端忽略（尤其注意 pressure / touch_major / touch_minor 是 int32，不是 float）。
//
// 同版本的官方全文同名文件随 SDK 一起发布（gitignore 的 build/bin 下）：
// build/bin/sdk/emulator/lib/emulator_controller.proto —— 修改本文件时应与它核对字段号与类型。
//
// 重新生成命令（Windows，protoc 25.3；-I 第二项是 protobuf 自带的 well-known types 目录）：
//
//	go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.36.11
//	go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.5.1
//	protoc -I internal/emulatorgrpc/proto \
//	  -I "D:/DeveEnvironment/Program/Anaconda3/Library/include" \
//	  --go_out=paths=source_relative:internal/emulatorgrpc/pb \
//	  --go-grpc_out=paths=source_relative:internal/emulatorgrpc/pb \
//	  internal/emulatorgrpc/proto/emulator_controller.proto
//
// 注意：protoc / protoc-gen-go / protoc-gen-go-grpc 必须都在 PATH 中；在 Windows 上
// go install 的产物位于 %GOPATH%\bin（通常是 C:\Users\<用户>\go\bin）。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: emulator_controller.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ImageFormat_ImgFormat int32

const (
	ImageFormat_PNG      ImageFormat_ImgFormat = 0
	ImageFormat_RGBA8888 ImageFormat_ImgFormat = 1
	ImageFormat_RGB888   ImageFormat_ImgFormat = 2
)

// Enum value maps for ImageFormat_ImgFormat.
var (
	ImageFormat_ImgFormat_name = map[int32]string{
		0: "PNG",
		1: "RGBA8888",
		2: "RGB888",
	}
	ImageFormat_ImgFormat_value = map[string]int32{
		"PNG":      0,
		"RGBA8888": 1,
		"RGB888":   2,
	}
)

func (x ImageFormat_ImgFormat) Enum() *ImageFormat_ImgFormat {
	p := new(ImageFormat_ImgFormat)
	*p = x
	return p
}

func (x ImageFormat_ImgFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ImageFormat_ImgFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_emulator_controller_proto_enumTypes[0].Descriptor()
}

func (ImageFormat_ImgFormat) Type() protoreflect.EnumType {
	return &file_emulator_controller_proto_enumTypes[0]
}

func (x ImageFormat_ImgFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ImageFormat_ImgFormat.Descriptor instead.
func (ImageFormat_ImgFormat) EnumDescriptor() ([]byte, []int) {
	return file_emulator_controller_proto_rawDescGZIP(), []int{0, 0}
}

// ImageFormat 描述请求的图像格式与尺寸。
type ImageFormat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Format        ImageFormat_ImgFormat  `protobuf:"varint,1,opt,name=format,proto3,enum=android.emulation.control.ImageFormat_ImgFormat" json:"format,omitempty"`
	Rotation      int32                  `protobuf:"varint,2,opt,name=rotation,proto3" json:"rotation,omitempty"`
	Width         uint32                 `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height        uint32                 `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	Display       int32                  `protobuf:"varint,5,opt,name=display,proto3" json:"display,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageFormat) Reset() {
	*x = ImageFormat{}
	mi := &file_emulator_controller_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageFormat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageFormat) ProtoMessage() {}

func (x *ImageFormat) ProtoReflect() protoreflect.Message {
	mi := &file_emulator_controller_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageFormat.ProtoReflect.Descriptor instead.
func (*ImageFormat) Descriptor() ([]byte, []int) {
	return file_emulator_controller_proto_rawDescGZIP(), []int{0}
}

func (x *ImageFormat) GetFormat() ImageFormat_ImgFormat {
	if x != nil {
		return x.Format
	}
	return ImageFormat_PNG
}

func (x *ImageFormat) GetRotation() int32 {
	if x != nil {
		return x.Rotation
	}
	return 0
}

func (x *ImageFormat) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *ImageFormat) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *ImageFormat) GetDisplay() int32 {
	if x != nil {
		return x.Display
	}
	return 0
}

// Image 是一帧图像。
type Image struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Format        *ImageFormat           `protobuf:"bytes,1,opt,name=format,proto3" json:"format,omitempty"`
	Width         uint32                 `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height        uint32                 `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Image         []byte                 `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	Seq           uint32                 `protobuf:"varint,5,opt,name=seq,proto3" json:"seq,omitempty"`
	TimestampUs   int64                  `protobuf:"varint,6,opt,name=timestampUs,proto3" json:"timestampUs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Image) Reset() {
	*x = Image{}
	mi := &file_emulator_controller_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Image) ProtoMessage() {}

func (x *Image) ProtoReflect() protoreflect.Message {
	mi := &file_emulator_controller_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Image.ProtoReflect.Descriptor instead.
func (*Image) Descriptor() ([]byte, []int) {
	return file_emulator_controller_proto_rawDescGZIP(), []int{1}
}

func (x *Image) GetFormat() *ImageFormat {
	if x != nil {
		return x.Format
	}
	return nil
}

func (x *Image) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Image) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Image) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *Image) GetSeq() uint32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Image) GetTimestampUs() int64 {
	if x != nil {
		return x.TimestampUs
	}
	return 0
}

// Touch 是单个触点。
type Touch struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	X     int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y     int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	// identifier 是触点标识（同一手势内需唯一）。
	Identifier int32 `protobuf:"varint,3,opt,name=identifier,proto3" json:"identifier,omitempty"`
	// pressure 是按 0 - 1<<15 量程解析的裸值：接触期间必须非零，
	// 结束该触点时必须置 0，否则该 identifier 永远不会被注销。
	Pressure int32 `protobuf:"varint,4,opt,name=pressure,proto3" json:"pressure,omitempty"`
	// touch_major / touch_minor 是触点面积（可选项，0 表示不上报）。
	TouchMajor int32 `protobuf:"varint,5,opt,name=touch_major,json=touchMajor,proto3" json:"touch_major,omitempty"`
	TouchMinor int32 `protobuf:"varint,6,opt,name=touch_minor,json=touchMinor,proto3" json:"touch_minor,omitempty"`
	// expiration=NEVER_EXPIRE(1) 表示按下/移动，0 表示本次事件后过期（抬起）。
	Expiration    int32 `protobuf:"varint,7,opt,name=expiration,proto3" json:"expiration,omitempty"`
	Orientation   int32 `protobuf:"varint,8,opt,name=orientation,proto3" json:"orientation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Touch) Reset() {
	*x = Touch{}
	mi := &file_emulator_controller_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Touch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Touch) ProtoMessage() {}

func (x *Touch) ProtoReflect() protoreflect.Message {
	mi := &file_emulator_controller_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Touch.ProtoReflect.Descriptor instead.
func (*Touch) Descriptor() ([]byte, []int) {
	return file_emulator_controller_proto_rawDescGZIP(), []int{2}
}

func (x *Touch) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Touch) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Touch) GetIdentifier() int32 {
	if x != nil {
		return x.Identifier
	}
	return 0
}

func (x *Touch) GetPressure() int32 {
	if x != nil {
		return x.Pressure
	}
	return 0
}

func (x *Touch) GetTouchMajor() int32 {
	if x != nil {
		return x.TouchMajor
	}
	return 0
}

func (x *Touch) GetTouchMinor() int32 {
	if x != nil {
		return x.TouchMinor
	}
	return 0
}

func (x *Touch) GetExpiration() int32 {
	if x != nil {
		return x.Expiration
	}
	return 0
}

func (x *Touch) GetOrientation() int32 {
	if x != nil {
		return x.Orientation
	}
	return 0
}

// TouchEvent 是一次触点事件（可携带多指）。
type TouchEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Touches       []*Touch               `protobuf:"bytes,1,rep,name=touches,proto3" json:"touches,omitempty"`
	Display       int32                  `protobuf:"varint,2,opt,name=display,proto3" json:"display,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TouchEvent) Reset() {
	*x = TouchEvent{}
	mi := &file_emulator_controller_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TouchEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TouchEvent) ProtoMessage() {}

func (x *TouchEvent) ProtoReflect() protoreflect.Message {
	mi := &file_emulator_controller_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TouchEvent.ProtoReflect.Descriptor instead.
func (*TouchEvent) Descriptor() ([]byte, []int) {
	return file_emulator_controller_proto_rawDescGZIP(), []int{3}
}

func (x *TouchEvent) GetTouches() []*Touch {
	if x != nil {
		return x.Touches
	}
	return nil
}

func (x *TouchEvent) GetDisplay() int32 {
	if x != nil {
		return x.Display
	}
	return 0
}

var File_emulator_controller_proto protoreflect.FileDescriptor

const file_emulator_controller_proto_rawDesc = "" +
	"\n" +
	"\x19emulator_controller.proto\x12\x19android.emulation.control\x1a\x1bgoogle/protobuf/empty.proto\"\xeb\x01\n" +
	"\vImageFormat\x12H\n" +
	"\x06format\x18\x01 \x01(\x0e20.android.emulation.control.ImageFormat.ImgFormatR\x06format\x12\x1a\n" +
	"\brotation\x18\x02 \x01(\x05R\brotation\x12\x14\n" +
	"\x05width\x18\x03 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\rR\x06height\x12\x18\n" +
	"\adisplay\x18\x05 \x01(\x05R\adisplay\".\n" +
	"\tImgFormat\x12\a\n" +
	"\x03PNG\x10\x00\x12\f\n" +
	"\bRGBA8888\x10\x01\x12\n" +
	"\n" +
	"\x06RGB888\x10\x02\"\xbf\x01\n" +
	"\x05Image\x12>\n" +
	"\x06format\x18\x01 \x01(\v2&.android.emulation.control.ImageFormatR\x06format\x12\x14\n" +
	"\x05width\x18\x02 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x01(\rR\x06height\x12\x14\n" +
	"\x05image\x18\x04 \x01(\fR\x05image\x12\x10\n" +
	"\x03seq\x18\x05 \x01(\rR\x03seq\x12 \n" +
	"\vtimestampUs\x18\x06 \x01(\x03R\vtimestampUs\"\xe3\x01\n" +
	"\x05Touch\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\x12\x1e\n" +
	"\n" +
	"identifier\x18\x03 \x01(\x05R\n" +
	"identifier\x12\x1a\n" +
	"\bpressure\x18\x04 \x01(\x05R\bpressure\x12\x1f\n" +
	"\vtouch_major\x18\x05 \x01(\x05R\n" +
	"touchMajor\x12\x1f\n" +
	"\vtouch_minor\x18\x06 \x01(\x05R\n" +
	"touchMinor\x12\x1e\n" +
	"\n" +
	"expiration\x18\a \x01(\x05R\n" +
	"expiration\x12 \n" +
	"\vorientation\x18\b \x01(\x05R\vorientation\"b\n" +
	"\n" +
	"TouchEvent\x12:\n" +
	"\atouches\x18\x01 \x03(\v2 .android.emulation.control.TouchR\atouches\x12\x18\n" +
	"\adisplay\x18\x02 \x01(\x05R\adisplay2\x9b\x02\n" +
	"\x12EmulatorController\x12Y\n" +
	"\rgetScreenshot\x12&.android.emulation.control.ImageFormat\x1a .android.emulation.control.Image\x12^\n" +
	"\x10streamScreenshot\x12&.android.emulation.control.ImageFormat\x1a .android.emulation.control.Image0\x01\x12J\n" +
	"\tsendTouch\x12%.android.emulation.control.TouchEvent\x1a\x16.google.protobuf.EmptyB(Z&AVDDesktop/internal/emulatorgrpc/pb;pbb\x06proto3"

var (
	file_emulator_controller_proto_rawDescOnce sync.Once
	file_emulator_controller_proto_rawDescData []byte
)

func file_emulator_controller_proto_rawDescGZIP() []byte {
	file_emulator_controller_proto_rawDescOnce.Do(func() {
		file_emulator_controller_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_emulator_controller_proto_rawDesc), len(file_emulator_controller_proto_rawDesc)))
	})
	return file_emulator_controller_proto_rawDescData
}

var file_emulator_controller_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_emulator_controller_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_emulator_controller_proto_goTypes = []any{
	(ImageFormat_ImgFormat)(0), // 0: android.emulation.control.ImageFormat.ImgFormat
	(*ImageFormat)(nil),        // 1: android.emulation.control.ImageFormat
	(*Image)(nil),              // 2: android.emulation.control.Image
	(*Touch)(nil),              // 3: android.emulation.control.Touch
	(*TouchEvent)(nil),         // 4: android.emulation.control.TouchEvent
	(*emptypb.Empty)(nil),      // 5: google.protobuf.Empty
}
var file_emulator_controller_proto_depIdxs = []int32{
	0, // 0: android.emulation.control.ImageFormat.format:type_name -> android.emulation.control.ImageFormat.ImgFormat
	1, // 1: android.emulation.control.Image.format:type_name -> android.emulation.control.ImageFormat
	3, // 2: android.emulation.control.TouchEvent.touches:type_name -> android.emulation.control.Touch
	1, // 3: android.emulation.control.EmulatorController.getScreenshot:input_type -> android.emulation.control.ImageFormat
	1, // 4: android.emulation.control.EmulatorController.streamScreenshot:input_type -> android.emulation.control.ImageFormat
	4, // 5: android.emulation.control.EmulatorController.sendTouch:input_type -> android.emulation.control.TouchEvent
	2, // 6: android.emulation.control.EmulatorController.getScreenshot:output_type -> android.emulation.control.Image
	2, // 7: android.emulation.control.EmulatorController.streamScreenshot:output_type -> android.emulation.control.Image
	5, // 8: android.emulation.control.EmulatorController.sendTouch:output_type -> google.protobuf.Empty
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_emulator_controller_proto_init() }
func file_emulator_controller_proto_init() {
	if File_emulator_controller_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_emulator_controller_proto_rawDesc), len(file_emulator_controller_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_emulator_controller_proto_goTypes,
		DependencyIndexes: file_emulator_controller_proto_depIdxs,
		EnumInfos:         file_emulator_controller_proto_enumTypes,
		MessageInfos:      file_emulator_controller_proto_msgTypes,
	}.Build()
	File_emulator_controller_proto = out.File
	file_emulator_controller_proto_goTypes = nil
	file_emulator_controller_proto_depIdxs = nil
}
